Article/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=120)
    # author = models.CharField(max_length=50)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=False, null=False)
    priority = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # author = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

Article/forms.py
from django import forms

from .models import Article
from django.contrib.auth.models import User


class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label='',
        widget=forms.TextInput(
            attrs={
                "placeholder": "Your title"
            }
        )
    )
    # author = forms.CharField(
    #     label='',
    #     widget=forms.TextInput(
    #         attrs={
    #             "placeholder": "Article's author",
    #         }
    #     ),
    # )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "article-content",
                "rows": 20,
                "cols": 120
            }
        )
    )

    class Meta:
        model = Article
        fields = [
            'title',
            'content',
            'priority'
        ]


class OptionForComments(forms.Form):
    users = User.objects.all()
    CHOICES = [(user.id, user.username) for user in users]
    default_user = users.first()
    initial_value = default_user.id if default_user else None
    filter_option = forms.ChoiceField(
        choices=[('', 'Select a user (All comments)')] + CHOICES,
        required=False,
        initial=initial_value
    )

Article/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Article, Comment
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User

from .forms import ArticleForm, OptionForComments


def article_list_view(request):
    articles = Article.objects.all().order_by('-priority', '-created_at')
    comments = Comment.objects.all().order_by('-created_at')
    k_comments = []
    seen_articles = set()
    for comment in comments:
        article_id = comment.article_id
        if article_id not in seen_articles:
            seen_articles.add(article_id)
            k_comments.append(comment)
    context = {
        'object_list': articles,
        'comments': k_comments
    }
    return render(request, "articles/article_list.html", context)


def article_view(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    comments = Comment.objects.all().filter(article=article.id).order_by('-created_at')
    context = {
        'article': article,
        'comments': comments
    }
    return render(request, 'articles/article.html', context)


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    article_id = comment.article_id
    if request.method == 'POST':
        comment.delete()
        return redirect('article', article_id)

    return render(request, 'articles/delete_comment.html', {'comment': comment})


@login_required
def add_comment(request):
    if request.method == 'POST':
        article_id = request.POST.get('article_id')
        author = request.user
        content = request.POST.get('content')

        article = get_object_or_404(Article, pk=article_id)

        Comment.objects.create(
            article=article,
            author=author,
            content=content,
        )

        return redirect('article', article_id)

    return redirect('article-list')


class ArticleCreateView(CreateView):
    model = Article
    template_name = 'articles/create_article.html'
    fields = ['title', 'content', 'priority']


@login_required
def add_article(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect('article-list')
    else:
        form = ArticleForm()

    return render(request, 'articles/create_article.html', {'form': form})


def all_comments(request):
    # users = User.objects.all()

    if request.method == 'GET':
        form = OptionForComments(request.GET)
        # form.files['filter_option'].choices = [(user.id, user.username) for user in users]

        if form.is_valid():
            selected_user_id = form.cleaned_data['filter_option']
            if selected_user_id:
                comments = Comment.objects.filter(author__id=selected_user_id).order_by('-created_at')
                for a in comments:
                    print(a)
            else:
                comments = Comment.objects.order_by('-created_at')

        else:
            comments = Comment.objects.order_by('-created_at')
    else:
        form = OptionForComments()
        comments = Comment.objects.order_by('-created_at')

    context = {
        'comments': comments,
        'form': form
    }

    return render(request, 'articles/all_comments.html', context)

Article/templates/articles/all_comments.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    {% endblock %}
    <br>
    <form method="get" action="">
        {% csrf_token %}
        {{ form.filter_option }}
        <button type="submit">Show comments</button>
    </form>
    {% if comments %}
        {% for comment in comments %}
            <ul class="comment">
                <strong>{{ comment.article.title }}</strong>
                <br>
                <i>{{ comment.author }}</i> ({{ comment.created_at }})
                <br>
                <p>{{ comment.content }}</p>
            </ul>
        {% endfor %}
    {% else %}
        <p>No comments found.</p>
    {% endif %}



{% endblock %}

Article/templates/articles/article.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/article_list.css' %}">
{% endblock %}
<script src="{% static 'comments_toggle.js' %}"></script>
<!--
    <form method="get" action="{% url 'create_article' %}">
        <button type="submit">New Article</button>
    </form>
-->
<br>
<div class="d-grid gap-2 col-2 mx-auto">
    <a href="{% url 'article-list' %}" class="btn btn-primary btn-lg" tabindex="-1" role="button" aria-disabled="true">Back to Home</a>
</div>
<br>
{% if article %}

    {% if article.priority %}
    <div class="card text-center bg-info" style="width: 70rem; background-color: rgba(232,184,184,0.5)!important;" >
      <div class="card-header" style="background-color:rgba(232,184,184,0.70)!important;text-align: left;">
        <strong>{{ article.author }}</strong> ({{ article.created_at }})
      </div>
      <div class="card-body" style="background-color:rgba(234,217,217,0.9)!important;">
    {% else %}
    <div class="card text-center bg-light" style="width: 70rem; background-color:rgba(113,144,182,0.5)!important;">
      <div class="card-header" style="background-color:rgba(113,144,182,0.70)!important;text-align: left;">
        <strong>{{ article.author }}</strong> ({{ article.created_at }})
      </div>
      <div class="card-body" style="background-color:rgba(193,213,245,0.9)!important;">
    {% endif %}
        <h5 class="card-title">{{ article.title }}</h5>
          <hr>
        <p class="card-text">{{ article.content }}</p>
      </div>
        <div class="card-footer align-left">
            {% if user.is_authenticated %}
                <br>
                <form method="post" action="{% url 'add_comment' %}">
                    {% csrf_token %}
                    <input type="hidden" name="article_id" value="{{ article.id }}">
                    <div class="mb-3">
                      <label for="exampleFormControlInput1 author" class="form-label">Your name: <b>{{ user.username }}</b></label>
                      <input type="hidden" name="author" class="form-control" id="exampleFormControlInput1" value="{{ user.username }}">
                    </div>
                    <div class="mb-3">
                      <textarea name="content" class="form-control" id="exampleFormControlTextarea1" rows="3" required></textarea>
                    </div>
                    <div class="col-12">
                      <button type="submit" class="btn btn-primary">Add comment</button>
                    </div>
                </form>
            {% endif %}
            <br>
            <h5 style="text-align: left; margin: auto; padding: 10px;"> All comments: {{ article.comment_set.count}}</h5>


            <div class="card-body comments comment" style="background-color:rgba(113,144,182,0.1)!important;">
                {% if article.comment_set.count != 0 %}
                        <p style="background-color:rgba(234,217,217,0.95)!important;">
                            {% for comment in comments %}
                                {% if comment.article == article %}
                                    <div class="card text-center bg-info comment" style="background-color: rgba(189,209,224,0.3)!important;" >
                                        <div class="card-header" style="background-color:rgba(126,225,94,0.95)!important;text-align: left">
                                            <strong>{{ article.author }}</strong> ({{ article.created_at }})
                                            {% if user.is_authenticated and user.is_staff %}
                                                <a href="{% url 'delete_comment' comment_id=comment.id %}">[Delete]</a>
                                            {% endif %}
                                        </div>
                                        <div class="card-footer align-left" style="background-color:rgba(175,232,156,0.95)!important; text-align: left">
                                            {{ comment.content }}
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </p>
                {% endif %}
            </div>






{#            {% if article.comment_set.count != 0 %}#}
{#                <p><button class="showCommentsButton btn btn-primary" data-article-id="{{ article.id }}">Show Comments</button></p>#}
{#            {% endif %}#}
{#            <div class="card-body comments comment" style="background-color:rgba(113,144,182,0.95)!important; display: none">#}
{#                {% if article.comment_set.count != 0 %}#}
{#                    <hr>#}
{#                        <p style="background-color:rgba(234,217,217,0.95)!important;">#}
{#                            {% for comment in comments %}#}
{#                                {% if comment.article == article %}#}
{#                                    <ul class="comment" style="display: none;">#}
{#                                        {% if user.is_authenticated and user.is_staff %}#}
{#                                            <p><a href="{% url 'delete_comment' comment_id=comment.id %}">Delete Comment</a></p>#}
{#                                        {% endif %}#}
{#                                        <strong>{{ comment.author }}</strong> ({{ comment.created_at }})#}
{#                                        <hr>#}
{#                                        {{ comment.content }}#}
{#                                    </ul>#}
{#                                {% endif %}#}
{#                            {% endfor %}#}
{#                        </p>#}
{#                {% endif %}#}
{#            </div>#}
        </div>

    </div>

{% endif %}


{% endblock %}

Article/templates/articles/article_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/article_list.css' %}">
{% endblock %}
<script src="{% static 'comments_toggle.js' %}"></script>

<!--
    <form method="get" action="{% url 'create_article' %}">
        <button type="submit">New Article</button>
    </form>
-->
{% for article in object_list %}

    {% if article.priority %}
    <div class="card text-center bg-info" style="width: 70rem; background-color:rgba(232,184,184,0.70)!important;">
    {% else %}
    <div class="card text-center bg-light" style="width: 70rem; background-color:rgba(113,144,182,0.70)!important;">
    {% endif %}
      <div class="card-header" style="text-align: left;">
        <strong>{{ article.author }}</strong> ({{ article.created_at }})
      </div>
      {% if article.priority %}
      <div class="card-body" style="background-color:rgba(234,217,217,0.95)!important;">
      {% else %}
      <div class="card-body" style="background-color:rgba(193,213,245,0.95)!important;">
      {% endif %}
        <h5 class="card-title">{{ article.title }}</h5>
          <hr>
        <p class="card-text">{{ article.content }}</p>
        <a href="{{ article.id }}/" class="btn btn-primary">Go to the article</a>
      </div>
        <div class="card-footer">
            Comments: {{ article.comment_set.count}}
            {% if article.comment_set.count != 0 %}
                <hr>
                    {% if article.priority %}
                    <p class="comment" style="background-color:rgba(241,237,237,0.7)!important;text-align: left">
                    {% else %}
                    <p class="comment" style="background-color:rgba(193,213,245,0.7)!important;text-align: left">
                    {% endif %}
                        {% for comment in comments %}
                            {% if comment.article == article %}
                                <b>{{ comment.author }}</b> ({{ comment.created_at }})
                                <br>
                                {{ comment.content }}
                            {% endif %}
                        {% endfor %}
                    </p>
            {% endif %}
        </div>
    </div>



{#    {% if article.priority %}#}
{#        <div class="article-content priority" onclick="window.location.href='{{ article.id }}/'">#}
{#    {% else %}#}
{#        <div class="article-content card" onclick="window.location.href='{{ article.id }}/'">#}
{#    {% endif %}#}
{#        <div class="card-body">#}
{#            <span class="comment-meta"><strong>{{ article.author }}</strong> ({{ article.created_at }})<br>#}
{#                {% if article.priority %}#}
{#                    <span class="article-title text-danger"><b>{{ article.title|upper }}</b></span>#}
{#                {% else %}#}
{#                    <span class="article-title">{{ article.title }}</span>#}
{#                {% endif %}#}
{#            </span>#}
{#            ({{ article.id }})#}
{#            <hr>#}
{#            <p class="card-text">{{ article.content }}</p>#}
{#            <strong class="mt-3">Comments ({{ article.comment_set.count }}):</strong>#}
{#            {% if article.comment_set.count != 0 %}#}
{#                <p><i>Last comment:</i> <br>#}
{#                    {% for comment in comments %}#}
{#                        {% if comment.article == article %}#}
{#                            <ul class="comment">#}
{#                                <li>#}
{#                                    <strong>{{ comment.author }}</strong> ({{ comment.created_at }})#}
{#                                    <hr>#}
{#                                    {{ comment.content }}#}
{#                                </li>#}
{#                            </ul>#}
{#                        {% endif %}#}
{#                    {% endfor %}#}
{#                </p>#}
{#            {% endif %}#}
{#        </div>#}
{#    </div>#}
{% endfor %}

{% endblock %}

Article/templates/articles/create_article.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    {% endblock %}
    <form class="center-form" method="POST" action="{% url 'add_article' %}"> {% csrf_token %}
        <b>Create a New Article</b>
{#        {{ form.as_p }}#}
        {{ form.title.label_tag }} {{ form.title }}
        {{ form.content.label_tag }} {{ form.content }}
        {% if user.is_authenticated and user.is_staff %}
            {{ form.priority.label_tag }} {{ form.priority }}
        {% endif %}
        <button type="submit">Create Article</button>
    </form>
    <br>
    <a href="{% url 'article-list' %}">
        <button type="button">Back to Article List</button>
    </a>
{% endblock %}

Article/templates/articles/delete_comment.html
{% extends 'base.html' %}

{% block content %}
    <h2>Delete Comment</h2>
    <form method="post" action="{% url 'delete_comment' comment.id %}">
        {% csrf_token %}
        <p>Are you sure you want to delete this comment?</p>
        <button type="submit">Yes, delete</button>
        <a href="{% url 'article' article_id=comment.article.id %}">Cancel</a>
    </form>
{% endblock %}